// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: samplea.proto

package com.agregsandbox.modela;

/**
 * Protobuf type {@code com.agregsandbox.modela.FactWrapper2}
 */
public  final class FactWrapper2 extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.agregsandbox.modela.FactWrapper2)
    FactWrapper2OrBuilder {
private static final long serialVersionUID = 0L;
  // Use FactWrapper2.newBuilder() to construct.
  private FactWrapper2(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FactWrapper2() {
    topic_ = "";
    prefix_ = "";
    key_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new FactWrapper2();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FactWrapper2(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            topic_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            prefix_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            key_ = s;
            break;
          }
          case 162: {
            com.agregsandbox.modela.FactA.Builder subBuilder = null;
            if (factA_ != null) {
              subBuilder = factA_.toBuilder();
            }
            factA_ = input.readMessage(com.agregsandbox.modela.FactA.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(factA_);
              factA_ = subBuilder.buildPartial();
            }

            break;
          }
          case 170: {
            com.agregsandbox.modela.FactB.Builder subBuilder = null;
            if (factB_ != null) {
              subBuilder = factB_.toBuilder();
            }
            factB_ = input.readMessage(com.agregsandbox.modela.FactB.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(factB_);
              factB_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.agregsandbox.modela.Samplea.internal_static_com_agregsandbox_modela_FactWrapper2_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.agregsandbox.modela.Samplea.internal_static_com_agregsandbox_modela_FactWrapper2_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.agregsandbox.modela.FactWrapper2.class, com.agregsandbox.modela.FactWrapper2.Builder.class);
  }

  public static final int TOPIC_FIELD_NUMBER = 1;
  private volatile java.lang.Object topic_;
  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  public com.google.protobuf.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PREFIX_FIELD_NUMBER = 2;
  private volatile java.lang.Object prefix_;
  /**
   * <code>string prefix = 2;</code>
   * @return The prefix.
   */
  public java.lang.String getPrefix() {
    java.lang.Object ref = prefix_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      prefix_ = s;
      return s;
    }
  }
  /**
   * <code>string prefix = 2;</code>
   * @return The bytes for prefix.
   */
  public com.google.protobuf.ByteString
      getPrefixBytes() {
    java.lang.Object ref = prefix_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      prefix_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int KEY_FIELD_NUMBER = 3;
  private volatile java.lang.Object key_;
  /**
   * <code>string key = 3;</code>
   * @return The key.
   */
  public java.lang.String getKey() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      key_ = s;
      return s;
    }
  }
  /**
   * <code>string key = 3;</code>
   * @return The bytes for key.
   */
  public com.google.protobuf.ByteString
      getKeyBytes() {
    java.lang.Object ref = key_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      key_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FACTA_FIELD_NUMBER = 20;
  private com.agregsandbox.modela.FactA factA_;
  /**
   * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
   * @return Whether the factA field is set.
   */
  public boolean hasFactA() {
    return factA_ != null;
  }
  /**
   * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
   * @return The factA.
   */
  public com.agregsandbox.modela.FactA getFactA() {
    return factA_ == null ? com.agregsandbox.modela.FactA.getDefaultInstance() : factA_;
  }
  /**
   * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
   */
  public com.agregsandbox.modela.FactAOrBuilder getFactAOrBuilder() {
    return getFactA();
  }

  public static final int FACTB_FIELD_NUMBER = 21;
  private com.agregsandbox.modela.FactB factB_;
  /**
   * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
   * @return Whether the factB field is set.
   */
  public boolean hasFactB() {
    return factB_ != null;
  }
  /**
   * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
   * @return The factB.
   */
  public com.agregsandbox.modela.FactB getFactB() {
    return factB_ == null ? com.agregsandbox.modela.FactB.getDefaultInstance() : factB_;
  }
  /**
   * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
   */
  public com.agregsandbox.modela.FactBOrBuilder getFactBOrBuilder() {
    return getFactB();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTopicBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, topic_);
    }
    if (!getPrefixBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, prefix_);
    }
    if (!getKeyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, key_);
    }
    if (factA_ != null) {
      output.writeMessage(20, getFactA());
    }
    if (factB_ != null) {
      output.writeMessage(21, getFactB());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTopicBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, topic_);
    }
    if (!getPrefixBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, prefix_);
    }
    if (!getKeyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, key_);
    }
    if (factA_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(20, getFactA());
    }
    if (factB_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(21, getFactB());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.agregsandbox.modela.FactWrapper2)) {
      return super.equals(obj);
    }
    com.agregsandbox.modela.FactWrapper2 other = (com.agregsandbox.modela.FactWrapper2) obj;

    if (!getTopic()
        .equals(other.getTopic())) return false;
    if (!getPrefix()
        .equals(other.getPrefix())) return false;
    if (!getKey()
        .equals(other.getKey())) return false;
    if (hasFactA() != other.hasFactA()) return false;
    if (hasFactA()) {
      if (!getFactA()
          .equals(other.getFactA())) return false;
    }
    if (hasFactB() != other.hasFactB()) return false;
    if (hasFactB()) {
      if (!getFactB()
          .equals(other.getFactB())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + PREFIX_FIELD_NUMBER;
    hash = (53 * hash) + getPrefix().hashCode();
    hash = (37 * hash) + KEY_FIELD_NUMBER;
    hash = (53 * hash) + getKey().hashCode();
    if (hasFactA()) {
      hash = (37 * hash) + FACTA_FIELD_NUMBER;
      hash = (53 * hash) + getFactA().hashCode();
    }
    if (hasFactB()) {
      hash = (37 * hash) + FACTB_FIELD_NUMBER;
      hash = (53 * hash) + getFactB().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.agregsandbox.modela.FactWrapper2 parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agregsandbox.modela.FactWrapper2 parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agregsandbox.modela.FactWrapper2 parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agregsandbox.modela.FactWrapper2 parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agregsandbox.modela.FactWrapper2 parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agregsandbox.modela.FactWrapper2 parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agregsandbox.modela.FactWrapper2 parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.agregsandbox.modela.FactWrapper2 parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.agregsandbox.modela.FactWrapper2 parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.agregsandbox.modela.FactWrapper2 parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.agregsandbox.modela.FactWrapper2 parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.agregsandbox.modela.FactWrapper2 parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.agregsandbox.modela.FactWrapper2 prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.agregsandbox.modela.FactWrapper2}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.agregsandbox.modela.FactWrapper2)
      com.agregsandbox.modela.FactWrapper2OrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.agregsandbox.modela.Samplea.internal_static_com_agregsandbox_modela_FactWrapper2_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.agregsandbox.modela.Samplea.internal_static_com_agregsandbox_modela_FactWrapper2_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.agregsandbox.modela.FactWrapper2.class, com.agregsandbox.modela.FactWrapper2.Builder.class);
    }

    // Construct using com.agregsandbox.modela.FactWrapper2.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      topic_ = "";

      prefix_ = "";

      key_ = "";

      if (factABuilder_ == null) {
        factA_ = null;
      } else {
        factA_ = null;
        factABuilder_ = null;
      }
      if (factBBuilder_ == null) {
        factB_ = null;
      } else {
        factB_ = null;
        factBBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.agregsandbox.modela.Samplea.internal_static_com_agregsandbox_modela_FactWrapper2_descriptor;
    }

    @java.lang.Override
    public com.agregsandbox.modela.FactWrapper2 getDefaultInstanceForType() {
      return com.agregsandbox.modela.FactWrapper2.getDefaultInstance();
    }

    @java.lang.Override
    public com.agregsandbox.modela.FactWrapper2 build() {
      com.agregsandbox.modela.FactWrapper2 result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.agregsandbox.modela.FactWrapper2 buildPartial() {
      com.agregsandbox.modela.FactWrapper2 result = new com.agregsandbox.modela.FactWrapper2(this);
      result.topic_ = topic_;
      result.prefix_ = prefix_;
      result.key_ = key_;
      if (factABuilder_ == null) {
        result.factA_ = factA_;
      } else {
        result.factA_ = factABuilder_.build();
      }
      if (factBBuilder_ == null) {
        result.factB_ = factB_;
      } else {
        result.factB_ = factBBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.agregsandbox.modela.FactWrapper2) {
        return mergeFrom((com.agregsandbox.modela.FactWrapper2)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.agregsandbox.modela.FactWrapper2 other) {
      if (other == com.agregsandbox.modela.FactWrapper2.getDefaultInstance()) return this;
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        onChanged();
      }
      if (!other.getPrefix().isEmpty()) {
        prefix_ = other.prefix_;
        onChanged();
      }
      if (!other.getKey().isEmpty()) {
        key_ = other.key_;
        onChanged();
      }
      if (other.hasFactA()) {
        mergeFactA(other.getFactA());
      }
      if (other.hasFactB()) {
        mergeFactB(other.getFactB());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.agregsandbox.modela.FactWrapper2 parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.agregsandbox.modela.FactWrapper2) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object topic_ = "";
    /**
     * <code>string topic = 1;</code>
     * @return The topic.
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic = 1;</code>
     * @return The bytes for topic.
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topic = 1;</code>
     * @param value The topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopic(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      topic_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic() {
      
      topic_ = getDefaultInstance().getTopic();
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 1;</code>
     * @param value The bytes for topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      topic_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object prefix_ = "";
    /**
     * <code>string prefix = 2;</code>
     * @return The prefix.
     */
    public java.lang.String getPrefix() {
      java.lang.Object ref = prefix_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        prefix_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string prefix = 2;</code>
     * @return The bytes for prefix.
     */
    public com.google.protobuf.ByteString
        getPrefixBytes() {
      java.lang.Object ref = prefix_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        prefix_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string prefix = 2;</code>
     * @param value The prefix to set.
     * @return This builder for chaining.
     */
    public Builder setPrefix(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      prefix_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string prefix = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearPrefix() {
      
      prefix_ = getDefaultInstance().getPrefix();
      onChanged();
      return this;
    }
    /**
     * <code>string prefix = 2;</code>
     * @param value The bytes for prefix to set.
     * @return This builder for chaining.
     */
    public Builder setPrefixBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      prefix_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object key_ = "";
    /**
     * <code>string key = 3;</code>
     * @return The key.
     */
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        key_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string key = 3;</code>
     * @return The bytes for key.
     */
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string key = 3;</code>
     * @param value The key to set.
     * @return This builder for chaining.
     */
    public Builder setKey(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      key_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string key = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearKey() {
      
      key_ = getDefaultInstance().getKey();
      onChanged();
      return this;
    }
    /**
     * <code>string key = 3;</code>
     * @param value The bytes for key to set.
     * @return This builder for chaining.
     */
    public Builder setKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      key_ = value;
      onChanged();
      return this;
    }

    private com.agregsandbox.modela.FactA factA_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.agregsandbox.modela.FactA, com.agregsandbox.modela.FactA.Builder, com.agregsandbox.modela.FactAOrBuilder> factABuilder_;
    /**
     * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
     * @return Whether the factA field is set.
     */
    public boolean hasFactA() {
      return factABuilder_ != null || factA_ != null;
    }
    /**
     * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
     * @return The factA.
     */
    public com.agregsandbox.modela.FactA getFactA() {
      if (factABuilder_ == null) {
        return factA_ == null ? com.agregsandbox.modela.FactA.getDefaultInstance() : factA_;
      } else {
        return factABuilder_.getMessage();
      }
    }
    /**
     * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
     */
    public Builder setFactA(com.agregsandbox.modela.FactA value) {
      if (factABuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        factA_ = value;
        onChanged();
      } else {
        factABuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
     */
    public Builder setFactA(
        com.agregsandbox.modela.FactA.Builder builderForValue) {
      if (factABuilder_ == null) {
        factA_ = builderForValue.build();
        onChanged();
      } else {
        factABuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
     */
    public Builder mergeFactA(com.agregsandbox.modela.FactA value) {
      if (factABuilder_ == null) {
        if (factA_ != null) {
          factA_ =
            com.agregsandbox.modela.FactA.newBuilder(factA_).mergeFrom(value).buildPartial();
        } else {
          factA_ = value;
        }
        onChanged();
      } else {
        factABuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
     */
    public Builder clearFactA() {
      if (factABuilder_ == null) {
        factA_ = null;
        onChanged();
      } else {
        factA_ = null;
        factABuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
     */
    public com.agregsandbox.modela.FactA.Builder getFactABuilder() {
      
      onChanged();
      return getFactAFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
     */
    public com.agregsandbox.modela.FactAOrBuilder getFactAOrBuilder() {
      if (factABuilder_ != null) {
        return factABuilder_.getMessageOrBuilder();
      } else {
        return factA_ == null ?
            com.agregsandbox.modela.FactA.getDefaultInstance() : factA_;
      }
    }
    /**
     * <code>.com.agregsandbox.modela.FactA factA = 20;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.agregsandbox.modela.FactA, com.agregsandbox.modela.FactA.Builder, com.agregsandbox.modela.FactAOrBuilder> 
        getFactAFieldBuilder() {
      if (factABuilder_ == null) {
        factABuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.agregsandbox.modela.FactA, com.agregsandbox.modela.FactA.Builder, com.agregsandbox.modela.FactAOrBuilder>(
                getFactA(),
                getParentForChildren(),
                isClean());
        factA_ = null;
      }
      return factABuilder_;
    }

    private com.agregsandbox.modela.FactB factB_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.agregsandbox.modela.FactB, com.agregsandbox.modela.FactB.Builder, com.agregsandbox.modela.FactBOrBuilder> factBBuilder_;
    /**
     * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
     * @return Whether the factB field is set.
     */
    public boolean hasFactB() {
      return factBBuilder_ != null || factB_ != null;
    }
    /**
     * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
     * @return The factB.
     */
    public com.agregsandbox.modela.FactB getFactB() {
      if (factBBuilder_ == null) {
        return factB_ == null ? com.agregsandbox.modela.FactB.getDefaultInstance() : factB_;
      } else {
        return factBBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
     */
    public Builder setFactB(com.agregsandbox.modela.FactB value) {
      if (factBBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        factB_ = value;
        onChanged();
      } else {
        factBBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
     */
    public Builder setFactB(
        com.agregsandbox.modela.FactB.Builder builderForValue) {
      if (factBBuilder_ == null) {
        factB_ = builderForValue.build();
        onChanged();
      } else {
        factBBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
     */
    public Builder mergeFactB(com.agregsandbox.modela.FactB value) {
      if (factBBuilder_ == null) {
        if (factB_ != null) {
          factB_ =
            com.agregsandbox.modela.FactB.newBuilder(factB_).mergeFrom(value).buildPartial();
        } else {
          factB_ = value;
        }
        onChanged();
      } else {
        factBBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
     */
    public Builder clearFactB() {
      if (factBBuilder_ == null) {
        factB_ = null;
        onChanged();
      } else {
        factB_ = null;
        factBBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
     */
    public com.agregsandbox.modela.FactB.Builder getFactBBuilder() {
      
      onChanged();
      return getFactBFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
     */
    public com.agregsandbox.modela.FactBOrBuilder getFactBOrBuilder() {
      if (factBBuilder_ != null) {
        return factBBuilder_.getMessageOrBuilder();
      } else {
        return factB_ == null ?
            com.agregsandbox.modela.FactB.getDefaultInstance() : factB_;
      }
    }
    /**
     * <code>.com.agregsandbox.modela.FactB factB = 21;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.agregsandbox.modela.FactB, com.agregsandbox.modela.FactB.Builder, com.agregsandbox.modela.FactBOrBuilder> 
        getFactBFieldBuilder() {
      if (factBBuilder_ == null) {
        factBBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.agregsandbox.modela.FactB, com.agregsandbox.modela.FactB.Builder, com.agregsandbox.modela.FactBOrBuilder>(
                getFactB(),
                getParentForChildren(),
                isClean());
        factB_ = null;
      }
      return factBBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.agregsandbox.modela.FactWrapper2)
  }

  // @@protoc_insertion_point(class_scope:com.agregsandbox.modela.FactWrapper2)
  private static final com.agregsandbox.modela.FactWrapper2 DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.agregsandbox.modela.FactWrapper2();
  }

  public static com.agregsandbox.modela.FactWrapper2 getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FactWrapper2>
      PARSER = new com.google.protobuf.AbstractParser<FactWrapper2>() {
    @java.lang.Override
    public FactWrapper2 parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FactWrapper2(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FactWrapper2> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FactWrapper2> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.agregsandbox.modela.FactWrapper2 getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

