// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: samplea.proto

package com.agregsandbox.modela;

public interface FactAOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.agregsandbox.modela.FactA)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nameA = 1;</code>
   * @return The nameA.
   */
  java.lang.String getNameA();
  /**
   * <code>string nameA = 1;</code>
   * @return The bytes for nameA.
   */
  com.google.protobuf.ByteString
      getNameABytes();
}
