// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: samplea.proto

package com.agregsandbox.modela;

public interface FactBOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.agregsandbox.modela.FactB)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string nameB = 1;</code>
   * @return The nameB.
   */
  java.lang.String getNameB();
  /**
   * <code>string nameB = 1;</code>
   * @return The bytes for nameB.
   */
  com.google.protobuf.ByteString
      getNameBBytes();
}
