// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: samplea.proto

package com.agregsandbox.modela;

public interface GatewayErrorAOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.agregsandbox.modela.GatewayErrorA)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string route = 1;</code>
   * @return The route.
   */
  java.lang.String getRoute();
  /**
   * <code>string route = 1;</code>
   * @return The bytes for route.
   */
  com.google.protobuf.ByteString
      getRouteBytes();

  /**
   * <code>string headers = 2;</code>
   * @return The headers.
   */
  java.lang.String getHeaders();
  /**
   * <code>string headers = 2;</code>
   * @return The bytes for headers.
   */
  com.google.protobuf.ByteString
      getHeadersBytes();

  /**
   * <code>string body = 3;</code>
   * @return The body.
   */
  java.lang.String getBody();
  /**
   * <code>string body = 3;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();

  /**
   * <code>string exMessage = 4;</code>
   * @return The exMessage.
   */
  java.lang.String getExMessage();
  /**
   * <code>string exMessage = 4;</code>
   * @return The bytes for exMessage.
   */
  com.google.protobuf.ByteString
      getExMessageBytes();

  /**
   * <code>string exStackTrace = 5;</code>
   * @return The exStackTrace.
   */
  java.lang.String getExStackTrace();
  /**
   * <code>string exStackTrace = 5;</code>
   * @return The bytes for exStackTrace.
   */
  com.google.protobuf.ByteString
      getExStackTraceBytes();

  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   * @return Whether the timestamp field is set.
   */
  boolean hasTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   * @return The timestamp.
   */
  com.google.protobuf.Timestamp getTimestamp();
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();
}
