// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sampleb.proto

package com.agregsandbox.modelb;

/**
 * Protobuf type {@code com.agregsandbox.modelb.GatewayErrorB}
 */
public  final class GatewayErrorB extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.agregsandbox.modelb.GatewayErrorB)
    GatewayErrorBOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GatewayErrorB.newBuilder() to construct.
  private GatewayErrorB(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GatewayErrorB() {
    route_ = "";
    headers_ = "";
    body_ = "";
    exMessage_ = "";
    exStackTrace_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GatewayErrorB();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GatewayErrorB(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            route_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            headers_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            body_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            exMessage_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            exStackTrace_ = s;
            break;
          }
          case 50: {
            com.google.protobuf.Timestamp.Builder subBuilder = null;
            if (timestamp_ != null) {
              subBuilder = timestamp_.toBuilder();
            }
            timestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(timestamp_);
              timestamp_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.agregsandbox.modelb.Sampleb.internal_static_com_agregsandbox_modelb_GatewayErrorB_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.agregsandbox.modelb.Sampleb.internal_static_com_agregsandbox_modelb_GatewayErrorB_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.agregsandbox.modelb.GatewayErrorB.class, com.agregsandbox.modelb.GatewayErrorB.Builder.class);
  }

  public static final int ROUTE_FIELD_NUMBER = 1;
  private volatile java.lang.Object route_;
  /**
   * <code>string route = 1;</code>
   * @return The route.
   */
  public java.lang.String getRoute() {
    java.lang.Object ref = route_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      route_ = s;
      return s;
    }
  }
  /**
   * <code>string route = 1;</code>
   * @return The bytes for route.
   */
  public com.google.protobuf.ByteString
      getRouteBytes() {
    java.lang.Object ref = route_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      route_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int HEADERS_FIELD_NUMBER = 2;
  private volatile java.lang.Object headers_;
  /**
   * <code>string headers = 2;</code>
   * @return The headers.
   */
  public java.lang.String getHeaders() {
    java.lang.Object ref = headers_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      headers_ = s;
      return s;
    }
  }
  /**
   * <code>string headers = 2;</code>
   * @return The bytes for headers.
   */
  public com.google.protobuf.ByteString
      getHeadersBytes() {
    java.lang.Object ref = headers_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      headers_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int BODY_FIELD_NUMBER = 3;
  private volatile java.lang.Object body_;
  /**
   * <code>string body = 3;</code>
   * @return The body.
   */
  public java.lang.String getBody() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      body_ = s;
      return s;
    }
  }
  /**
   * <code>string body = 3;</code>
   * @return The bytes for body.
   */
  public com.google.protobuf.ByteString
      getBodyBytes() {
    java.lang.Object ref = body_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      body_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXMESSAGE_FIELD_NUMBER = 4;
  private volatile java.lang.Object exMessage_;
  /**
   * <code>string exMessage = 4;</code>
   * @return The exMessage.
   */
  public java.lang.String getExMessage() {
    java.lang.Object ref = exMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      exMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string exMessage = 4;</code>
   * @return The bytes for exMessage.
   */
  public com.google.protobuf.ByteString
      getExMessageBytes() {
    java.lang.Object ref = exMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EXSTACKTRACE_FIELD_NUMBER = 5;
  private volatile java.lang.Object exStackTrace_;
  /**
   * <code>string exStackTrace = 5;</code>
   * @return The exStackTrace.
   */
  public java.lang.String getExStackTrace() {
    java.lang.Object ref = exStackTrace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      exStackTrace_ = s;
      return s;
    }
  }
  /**
   * <code>string exStackTrace = 5;</code>
   * @return The bytes for exStackTrace.
   */
  public com.google.protobuf.ByteString
      getExStackTraceBytes() {
    java.lang.Object ref = exStackTrace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      exStackTrace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 6;
  private com.google.protobuf.Timestamp timestamp_;
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   * @return Whether the timestamp field is set.
   */
  public boolean hasTimestamp() {
    return timestamp_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   * @return The timestamp.
   */
  public com.google.protobuf.Timestamp getTimestamp() {
    return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
  }
  /**
   * <code>.google.protobuf.Timestamp timestamp = 6;</code>
   */
  public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
    return getTimestamp();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getRouteBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, route_);
    }
    if (!getHeadersBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, headers_);
    }
    if (!getBodyBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, body_);
    }
    if (!getExMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, exMessage_);
    }
    if (!getExStackTraceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, exStackTrace_);
    }
    if (timestamp_ != null) {
      output.writeMessage(6, getTimestamp());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getRouteBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, route_);
    }
    if (!getHeadersBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, headers_);
    }
    if (!getBodyBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, body_);
    }
    if (!getExMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, exMessage_);
    }
    if (!getExStackTraceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, exStackTrace_);
    }
    if (timestamp_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getTimestamp());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.agregsandbox.modelb.GatewayErrorB)) {
      return super.equals(obj);
    }
    com.agregsandbox.modelb.GatewayErrorB other = (com.agregsandbox.modelb.GatewayErrorB) obj;

    if (!getRoute()
        .equals(other.getRoute())) return false;
    if (!getHeaders()
        .equals(other.getHeaders())) return false;
    if (!getBody()
        .equals(other.getBody())) return false;
    if (!getExMessage()
        .equals(other.getExMessage())) return false;
    if (!getExStackTrace()
        .equals(other.getExStackTrace())) return false;
    if (hasTimestamp() != other.hasTimestamp()) return false;
    if (hasTimestamp()) {
      if (!getTimestamp()
          .equals(other.getTimestamp())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ROUTE_FIELD_NUMBER;
    hash = (53 * hash) + getRoute().hashCode();
    hash = (37 * hash) + HEADERS_FIELD_NUMBER;
    hash = (53 * hash) + getHeaders().hashCode();
    hash = (37 * hash) + BODY_FIELD_NUMBER;
    hash = (53 * hash) + getBody().hashCode();
    hash = (37 * hash) + EXMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getExMessage().hashCode();
    hash = (37 * hash) + EXSTACKTRACE_FIELD_NUMBER;
    hash = (53 * hash) + getExStackTrace().hashCode();
    if (hasTimestamp()) {
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamp().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.agregsandbox.modelb.GatewayErrorB parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agregsandbox.modelb.GatewayErrorB parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agregsandbox.modelb.GatewayErrorB parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agregsandbox.modelb.GatewayErrorB parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agregsandbox.modelb.GatewayErrorB parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.agregsandbox.modelb.GatewayErrorB parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.agregsandbox.modelb.GatewayErrorB parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.agregsandbox.modelb.GatewayErrorB parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.agregsandbox.modelb.GatewayErrorB parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.agregsandbox.modelb.GatewayErrorB parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.agregsandbox.modelb.GatewayErrorB parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.agregsandbox.modelb.GatewayErrorB parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.agregsandbox.modelb.GatewayErrorB prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.agregsandbox.modelb.GatewayErrorB}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.agregsandbox.modelb.GatewayErrorB)
      com.agregsandbox.modelb.GatewayErrorBOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.agregsandbox.modelb.Sampleb.internal_static_com_agregsandbox_modelb_GatewayErrorB_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.agregsandbox.modelb.Sampleb.internal_static_com_agregsandbox_modelb_GatewayErrorB_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.agregsandbox.modelb.GatewayErrorB.class, com.agregsandbox.modelb.GatewayErrorB.Builder.class);
    }

    // Construct using com.agregsandbox.modelb.GatewayErrorB.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      route_ = "";

      headers_ = "";

      body_ = "";

      exMessage_ = "";

      exStackTrace_ = "";

      if (timestampBuilder_ == null) {
        timestamp_ = null;
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.agregsandbox.modelb.Sampleb.internal_static_com_agregsandbox_modelb_GatewayErrorB_descriptor;
    }

    @java.lang.Override
    public com.agregsandbox.modelb.GatewayErrorB getDefaultInstanceForType() {
      return com.agregsandbox.modelb.GatewayErrorB.getDefaultInstance();
    }

    @java.lang.Override
    public com.agregsandbox.modelb.GatewayErrorB build() {
      com.agregsandbox.modelb.GatewayErrorB result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.agregsandbox.modelb.GatewayErrorB buildPartial() {
      com.agregsandbox.modelb.GatewayErrorB result = new com.agregsandbox.modelb.GatewayErrorB(this);
      result.route_ = route_;
      result.headers_ = headers_;
      result.body_ = body_;
      result.exMessage_ = exMessage_;
      result.exStackTrace_ = exStackTrace_;
      if (timestampBuilder_ == null) {
        result.timestamp_ = timestamp_;
      } else {
        result.timestamp_ = timestampBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.agregsandbox.modelb.GatewayErrorB) {
        return mergeFrom((com.agregsandbox.modelb.GatewayErrorB)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.agregsandbox.modelb.GatewayErrorB other) {
      if (other == com.agregsandbox.modelb.GatewayErrorB.getDefaultInstance()) return this;
      if (!other.getRoute().isEmpty()) {
        route_ = other.route_;
        onChanged();
      }
      if (!other.getHeaders().isEmpty()) {
        headers_ = other.headers_;
        onChanged();
      }
      if (!other.getBody().isEmpty()) {
        body_ = other.body_;
        onChanged();
      }
      if (!other.getExMessage().isEmpty()) {
        exMessage_ = other.exMessage_;
        onChanged();
      }
      if (!other.getExStackTrace().isEmpty()) {
        exStackTrace_ = other.exStackTrace_;
        onChanged();
      }
      if (other.hasTimestamp()) {
        mergeTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.agregsandbox.modelb.GatewayErrorB parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.agregsandbox.modelb.GatewayErrorB) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object route_ = "";
    /**
     * <code>string route = 1;</code>
     * @return The route.
     */
    public java.lang.String getRoute() {
      java.lang.Object ref = route_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        route_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string route = 1;</code>
     * @return The bytes for route.
     */
    public com.google.protobuf.ByteString
        getRouteBytes() {
      java.lang.Object ref = route_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        route_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string route = 1;</code>
     * @param value The route to set.
     * @return This builder for chaining.
     */
    public Builder setRoute(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      route_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string route = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRoute() {
      
      route_ = getDefaultInstance().getRoute();
      onChanged();
      return this;
    }
    /**
     * <code>string route = 1;</code>
     * @param value The bytes for route to set.
     * @return This builder for chaining.
     */
    public Builder setRouteBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      route_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object headers_ = "";
    /**
     * <code>string headers = 2;</code>
     * @return The headers.
     */
    public java.lang.String getHeaders() {
      java.lang.Object ref = headers_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headers_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string headers = 2;</code>
     * @return The bytes for headers.
     */
    public com.google.protobuf.ByteString
        getHeadersBytes() {
      java.lang.Object ref = headers_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headers_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string headers = 2;</code>
     * @param value The headers to set.
     * @return This builder for chaining.
     */
    public Builder setHeaders(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      headers_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string headers = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHeaders() {
      
      headers_ = getDefaultInstance().getHeaders();
      onChanged();
      return this;
    }
    /**
     * <code>string headers = 2;</code>
     * @param value The bytes for headers to set.
     * @return This builder for chaining.
     */
    public Builder setHeadersBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      headers_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object body_ = "";
    /**
     * <code>string body = 3;</code>
     * @return The body.
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        body_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string body = 3;</code>
     * @return The bytes for body.
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string body = 3;</code>
     * @param value The body to set.
     * @return This builder for chaining.
     */
    public Builder setBody(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      body_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string body = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearBody() {
      
      body_ = getDefaultInstance().getBody();
      onChanged();
      return this;
    }
    /**
     * <code>string body = 3;</code>
     * @param value The bytes for body to set.
     * @return This builder for chaining.
     */
    public Builder setBodyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      body_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object exMessage_ = "";
    /**
     * <code>string exMessage = 4;</code>
     * @return The exMessage.
     */
    public java.lang.String getExMessage() {
      java.lang.Object ref = exMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string exMessage = 4;</code>
     * @return The bytes for exMessage.
     */
    public com.google.protobuf.ByteString
        getExMessageBytes() {
      java.lang.Object ref = exMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exMessage = 4;</code>
     * @param value The exMessage to set.
     * @return This builder for chaining.
     */
    public Builder setExMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      exMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string exMessage = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearExMessage() {
      
      exMessage_ = getDefaultInstance().getExMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string exMessage = 4;</code>
     * @param value The bytes for exMessage to set.
     * @return This builder for chaining.
     */
    public Builder setExMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      exMessage_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object exStackTrace_ = "";
    /**
     * <code>string exStackTrace = 5;</code>
     * @return The exStackTrace.
     */
    public java.lang.String getExStackTrace() {
      java.lang.Object ref = exStackTrace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exStackTrace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string exStackTrace = 5;</code>
     * @return The bytes for exStackTrace.
     */
    public com.google.protobuf.ByteString
        getExStackTraceBytes() {
      java.lang.Object ref = exStackTrace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exStackTrace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string exStackTrace = 5;</code>
     * @param value The exStackTrace to set.
     * @return This builder for chaining.
     */
    public Builder setExStackTrace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      exStackTrace_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string exStackTrace = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearExStackTrace() {
      
      exStackTrace_ = getDefaultInstance().getExStackTrace();
      onChanged();
      return this;
    }
    /**
     * <code>string exStackTrace = 5;</code>
     * @param value The bytes for exStackTrace to set.
     * @return This builder for chaining.
     */
    public Builder setExStackTraceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      exStackTrace_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp timestamp_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     * @return Whether the timestamp field is set.
     */
    public boolean hasTimestamp() {
      return timestampBuilder_ != null || timestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     * @return The timestamp.
     */
    public com.google.protobuf.Timestamp getTimestamp() {
      if (timestampBuilder_ == null) {
        return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      } else {
        return timestampBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder setTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamp_ = value;
        onChanged();
      } else {
        timestampBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder setTimestamp(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (timestampBuilder_ == null) {
        timestamp_ = builderForValue.build();
        onChanged();
      } else {
        timestampBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
      if (timestampBuilder_ == null) {
        if (timestamp_ != null) {
          timestamp_ =
            com.google.protobuf.Timestamp.newBuilder(timestamp_).mergeFrom(value).buildPartial();
        } else {
          timestamp_ = value;
        }
        onChanged();
      } else {
        timestampBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public Builder clearTimestamp() {
      if (timestampBuilder_ == null) {
        timestamp_ = null;
        onChanged();
      } else {
        timestamp_ = null;
        timestampBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
      
      onChanged();
      return getTimestampFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      if (timestampBuilder_ != null) {
        return timestampBuilder_.getMessageOrBuilder();
      } else {
        return timestamp_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getTimestampFieldBuilder() {
      if (timestampBuilder_ == null) {
        timestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getTimestamp(),
                getParentForChildren(),
                isClean());
        timestamp_ = null;
      }
      return timestampBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.agregsandbox.modelb.GatewayErrorB)
  }

  // @@protoc_insertion_point(class_scope:com.agregsandbox.modelb.GatewayErrorB)
  private static final com.agregsandbox.modelb.GatewayErrorB DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.agregsandbox.modelb.GatewayErrorB();
  }

  public static com.agregsandbox.modelb.GatewayErrorB getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GatewayErrorB>
      PARSER = new com.google.protobuf.AbstractParser<GatewayErrorB>() {
    @java.lang.Override
    public GatewayErrorB parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GatewayErrorB(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GatewayErrorB> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GatewayErrorB> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.agregsandbox.modelb.GatewayErrorB getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

