// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sampleb.proto

package com.agregsandbox.modelb;

public final class Sampleb {
  private Sampleb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_agregsandbox_modelb_GatewayErrorB_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_agregsandbox_modelb_GatewayErrorB_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_agregsandbox_modelb_MyMessageC_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_agregsandbox_modelb_MyMessageC_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_agregsandbox_modelb_MyMessageD_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_agregsandbox_modelb_MyMessageD_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rsampleb.proto\022\027com.agregsandbox.modelb" +
      "\032\037google/protobuf/timestamp.proto\"\225\001\n\rGa" +
      "tewayErrorB\022\r\n\005route\030\001 \001(\t\022\017\n\007headers\030\002 " +
      "\001(\t\022\014\n\004body\030\003 \001(\t\022\021\n\texMessage\030\004 \001(\t\022\024\n\014" +
      "exStackTrace\030\005 \001(\t\022-\n\ttimestamp\030\006 \001(\0132\032." +
      "google.protobuf.Timestamp\"U\n\nMyMessageC\022" +
      "\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022-\n\ttimestamp\030\003" +
      " \001(\0132\032.google.protobuf.Timestamp\"U\n\nMyMe" +
      "ssageD\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022-\n\ttime" +
      "stamp\030\003 \001(\0132\032.google.protobuf.TimestampB" +
      "\033\n\027com.agregsandbox.modelbP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_agregsandbox_modelb_GatewayErrorB_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_agregsandbox_modelb_GatewayErrorB_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_agregsandbox_modelb_GatewayErrorB_descriptor,
        new java.lang.String[] { "Route", "Headers", "Body", "ExMessage", "ExStackTrace", "Timestamp", });
    internal_static_com_agregsandbox_modelb_MyMessageC_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_agregsandbox_modelb_MyMessageC_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_agregsandbox_modelb_MyMessageC_descriptor,
        new java.lang.String[] { "Id", "Name", "Timestamp", });
    internal_static_com_agregsandbox_modelb_MyMessageD_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_agregsandbox_modelb_MyMessageD_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_agregsandbox_modelb_MyMessageD_descriptor,
        new java.lang.String[] { "Id", "Name", "Timestamp", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
